src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessagesRepository::class)]
class Messages
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $sender_id = null;

    #[ORM\Column]
    private ?int $recepient_id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSenderId(): ?Users
    {
        return $this->sender_id;
    }

    public function setSenderId(?Users $sender_id): self
    {
        $this->sender_id = $sender_id;

        return $this;
    }

    public function getRecepientId(): ?int
    {
        return $this->recepient_id;
    }

    public function setRecepientId(int $recepient_id): self
    {
        $this->recepient_id = $recepient_id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[Vich\Uploadable]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[Vich\UploadableField(mapping: "profile_img", fileNameProperty: "profile_img", size: "imageSize")]
    #[Assert\NotBlank()]
    #[Assert\Image(mimeTypes: ['image/jpeg', 'image/jpg'])]
    #[Assert\Image(maxSize: '2M')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 5, minMessage: "Name is too short" )]
    private ?string $fname = null;

    #[ORM\Column(length: 255)]
    // #[Assert\Length(min: 5, minMessage: "Name is too short !" )]
    private ?string $lname = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Assert\Email(message: "Invalid email !")]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\Regex(pattern: " /^\+221[0-9]{9}/ ", message: "invalid number !")]
    private ?string $phone = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 5, minMessage: "Password is too short !" )]
    private ?string $password = null;

    #[ORM\Column(options: ['default' => "0"])]
    private ?bool $status = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\Length(min: 50, minMessage: "Max. length: 50 !" )]
    private ?string $description = null;

    #[ORM\OneToMany(mappedBy: 'sender_id', targetEntity: Messages::class, orphanRemoval: true)]
    private Collection $messages;

    #[ORM\ManyToMany(targetEntity: UsersBlocked::class, mappedBy: 'user_bloking_id')]
    private Collection $usersBlockeds;

    #[ORM\ManyToMany(targetEntity: UsersDeleted::class, mappedBy: 'user_deleting_id')]
    private Collection $usersDeleteds;

    #[ORM\Column(length: 255)]
    private ?string $profile_img = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $back_img = null;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->usersBlockeds = new ArrayCollection();
        $this->usersDeleteds = new ArrayCollection();
    }

    public function getRoles(): array
    {
        return ["ROLE_USER"];
    }

    public function getUserIdentifier(): string
    {
        return "";
    }
    
    public function eraseCredentials()
    {
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFname(): ?string
    {
        return $this->fname;
    }

    public function setFname(string $fname): self
    {
        $this->fname = $fname;

        return $this;
    }

    public function getLname(): ?string
    {
        return $this->lname;
    }

    public function setLname(string $lname): self
    {
        $this->lname = $lname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Messages>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Messages $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setSenderId($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getSenderId() === $this) {
                $message->setSenderId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, UsersBlocked>
     */
    public function getUsersBlockeds(): Collection
    {
        return $this->usersBlockeds;
    }

    public function addUsersBlocked(UsersBlocked $usersBlocked): self
    {
        if (!$this->usersBlockeds->contains($usersBlocked)) {
            $this->usersBlockeds->add($usersBlocked);
            $usersBlocked->addUserBlockingId($this);
        }

        return $this;
    }

    public function removeUsersBlocked(UsersBlocked $usersBlocked): self
    {
        if ($this->usersBlockeds->removeElement($usersBlocked)) {
            $usersBlocked->removeUserBlokingId($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, UsersDeleted>
     */
    public function getUsersDeleteds(): Collection
    {
        return $this->usersDeleteds;
    }

    public function addUsersDeleted(UsersDeleted $usersDeleted): self
    {
        if (!$this->usersDeleteds->contains($usersDeleted)) {
            $this->usersDeleteds->add($usersDeleted);
            $usersDeleted->addUserDeletingId($this);
        }

        return $this;
    }

    public function removeUsersDeleted(UsersDeleted $usersDeleted): self
    {
        if ($this->usersDeleteds->removeElement($usersDeleted)) {
            $usersDeleted->removeUserDeletingId($this);
        }

        return $this;
    }

    /**
     * transforme l'objet en chaine 
     */
    public function serialize()
    {
        // on return les infos qu'on veut conserver au niveau du user
        return serialize([
            $this->id,
            $this->email,
            $this->password
        ]);
    }
    /**
     * transforme la chaine en objet 
     */
    public function unserialize(string $data_serialise)
    {
        // genraliser un user apartir des information serialiser, les rendre en objet (User)
        list(
            $this->id,
            $this->email,
            $this->password
        ) = unserialize($data_serialise, ['allow_classes' => false]); // false pour ne pas instancier les classes dans la unserialisation
    }

    public function getProfileImg(): ?string
    {
        return $this->profile_img;
    }

    public function setProfileImg(string $profile_img): self
    {
        $this->profile_img = $profile_img;

        return $this;
    }

    public function getBackImg(): ?string
    {
        return $this->back_img;
    }

    public function setBackImg(string $back_img): self
    {
        $this->back_img = $back_img;

        return $this;
    }

    /*
    * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
    */
   public function setImageFile(?File $imageFile = null): void
   {
       $this->imageFile = $imageFile;

       if (null !== $imageFile) {
           // It is required that at least one field changes if you are using doctrine
           // otherwise the event listeners won't be called and the file is lost
           $this->updatedAt = new \DateTimeImmutable();
       }
   }

   public function getImageFile(): ?File
   {
       return $this->imageFile;
   }

    /**
     * Get the value of imageSize
     */ 
    public function getImageSize()
    {
        return $this->imageSize;
    }

    /**
     * Set the value of imageSize
     *
     * @return  self
     */ 
    public function setImageSize($imageSize)
    {
        $this->imageSize = $imageSize;

        return $this;
    }

    /**
     * Get the value of updatedAt
     */ 
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set the value of updatedAt
     *
     * @return  self
     */ 
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

templates/pages/body-chat.html.twig
{% for m in messages %}

    {% if m.recepientId == user.id %}
        <div class="send">
            <p>{{ m.message|nl2br }} <span id="hour">{{ m.createdAt|date('H:i') }}</span></p>
        </div>
        
    {% else %}
        <div class="receive">
            <div class="receive-img">
                <img src="{{ vich_uploader_asset(user, 'imageFile' )}}" alt="{{user.fname}} {{user.lname}}">
            </div>
            <p>{{ m.message|nl2br }} <span id="hour">{{ m.createdAt|date('H:i') }}</span></p>
        </div>
    {% endif %}
{% endfor %}

templates/pages/last-message-send.html.twig
<div class="send">
    <p>{{ message.message|nl2br }} <span id="hour">{{ message.createdAt|date('H:i') }}</span></p>
</div>

templates/pages/message-section.html.twig
<div class="chat-section">
    <div class="header">
        
        <div class="user-status">
            <div class="show-hide-arrow-chat">
                <i class="fa-solid fa-arrow-left"></i>
            </div>
            <div class="user-status-img">
                <img src="{{ vich_uploader_asset(user, 'imageFile') }}" alt="{{user.fname}} {{user.lname}}">
            </div>
            <div class="user-details">
                <h3>{{user.fname}} {{user.lname}}</h3>
                {% if user.status == true %}
                    <p class="active">Online</p>
                {% else %}
                    <p class="inactive">Offline</p>
                {% endif %}
            </div>
        </div>
        <div class="icons">
            <!-- <div class="video">
                <i class="fa-solid fa-video"></i>
            </div> -->
            <!-- <div class="phone">
                <i class="fa-solid fa-phone"></i>
            </div> -->
            <div class="more">
                <i class="fa-solid fa-circle-info" id="open-profile"></i>
            </div>
            <div id="modal-user">
                <div class="profile-back">
                    {% if user.backImg == '' %}
                        {% set img = "img/back.jpg" %}
                    {% else %}
                        {% set img = vich_uploader_asset(user, 'imageFile') %}
                    {% endif %}
                    <div class="content-back" style="background-image: url('{{ img }}');">
                        <div class="content">
                            <div id="close-profile">
                                <i class="fa-solid fa-xmark"></i>
                            </div>
                        </div>
                        <div class="profile-img">
                            <img src="{{ vich_uploader_asset(user, 'imageFile')}} " width="35" height="35" alt="{{user.fname}} {{user.lname}}">
                        </div>
                    </div>
                    
                    <div class="profile-desc">
                        <h2>{{user.fname}} {{user.lname}}</h2>
                        <p>{{user.description}}</p>
                    </div>
                    <div class="profile-details">
                        <div class="detail-item">
                            <h3>Phone</h3>
                            <p>{{user.phone}}</p>
                        </div>
                        <div class="detail-item">
                            <h3>Email</h3>
                            <p>{{user.email}}</p>
                        </div>
                        <div class="detail-item">
                            <h3>Status</h3>
                            {% if user.status == true %}
                                <p>Online</p>
                            {% else %}
                                <p>Offline</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="body">

        {% if messages is not null %}
            {% for m in messages %}

                {% if m.recepientId == user.id %}
                    <div class="send">
                        <p>{{ m.message|nl2br }} <span id="hour">{{ m.createdAt|date('H:i') }}</span></p>
                    </div>
                    
                {% else %}
                    <div class="receive">
                        <div class="receive-img">
                            <img src="{{ vich_uploader_asset(user, 'imageFile' )}}" alt="{{user.fname}} {{user.lname}}">
                        </div>
                        <p>{{ m.message|nl2br }} <span id="hour">{{ m.createdAt|date('H:i') }}</span></p>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <p style="text-align: center; font-size: 30px; color: white; margin-top: 20%;">No Discussions</p>
        {% endif %}
        

        {# <div class="send">
            <audio src="" type="audio/webm" controls>
            </audio>
            <span id="hour-audio">12:45</span>
        </div>
        <div class="receive">
            <div class="receive-img">
                <img src="./img/back.jpg" alt="">
            </div>
            <audio src="" type="audio/webm" controls>
            </audio>
            <span id="hour-audio">12:45</span>
        </div> #}
        {# <div class="send">
            <img class="img-chat" src="./img/back.jpg" alt="">
        </div>
        <div class="receive">
            <div class="receive-img">
                <img src="./img/back.jpg" alt="">
            </div>
            <img class="img-chat" src="./img/back.jpg" alt="">
        </div> #}
    </div>
    <div class="footer">
        <div id="emoji">
            <i class="fa-regular fa-face-smile-beam"></i>
        </div>
        <div class="link">
            <i class="fa-solid fa-paperclip"></i>
        </div>
        <div class="form-chat-container">
            <form action="{{ path('form.chat', {id: user.id}) }}" method="post" id="form-chat" autocomplete="off">
                <input type="text" name="message" placeholder="Tape a message...">
                <input type="hidden" value="{{user.id}}" id="to">
                <input type="hidden" value="{{user_sending.id}}" id="from">
            </form>
            <div id="emoji-section">
                <ul>
                    <span id="emoji-close"><i class="fa-solid fa-xmark" ></i></span>
                </ul>
            </div>
        </div>
        <div class="microphone">
            <span id="micro"><i class="fa-solid fa-microphone" ></i></span>
            <span id="pause"><i class="fa-regular fa-pause-circle" ></i></span>
            <span id="play"><i class="fa-regular fa-play-circle" ></i></span>
            <span id="send"><i class="fa-regular fa-paper-plane" ></i></span>
        </div>
    </div>
</div>