src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[Vich\Uploadable]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[Vich\UploadableField(mapping: "profile_img", fileNameProperty: "profile_img", size: "imageSize")]
    #[Assert\NotBlank()]
    #[Assert\Image(mimeTypes: ['image/jpeg', 'image/jpg'])]
    #[Assert\Image(maxSize: '2M')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 5, minMessage: "Name is too short" )]
    private ?string $fname = null;

    #[ORM\Column(length: 255)]
    // #[Assert\Length(min: 5, minMessage: "Name is too short !" )]
    private ?string $lname = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Assert\Email(message: "Invalid email !")]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\Regex(pattern: " /^\+221[0-9]{9}/ ", message: "invalid number !")]
    private ?string $phone = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 5, minMessage: "Password is too short !" )]
    private ?string $password = null;

    #[ORM\Column(options: ['default' => "0"])]
    private ?bool $status = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\Length(min: 50, minMessage: "Max. length: 50 !" )]
    private ?string $description = null;

    #[ORM\OneToMany(mappedBy: 'sender_id', targetEntity: Messages::class, orphanRemoval: true)]
    private Collection $messages;

    #[ORM\ManyToMany(targetEntity: UsersBlocked::class, mappedBy: 'user_bloking_id')]
    private Collection $usersBlockeds;

    #[ORM\ManyToMany(targetEntity: UsersDeleted::class, mappedBy: 'user_deleting_id')]
    private Collection $usersDeleteds;

    #[ORM\Column(length: 255)]
    private ?string $profile_img = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $back_img = null;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->usersBlockeds = new ArrayCollection();
        $this->usersDeleteds = new ArrayCollection();
    }

    public function getRoles(): array
    {
        return ["ROLE_USER"];
    }

    public function getUserIdentifier(): string
    {
        return "";
    }
    
    public function eraseCredentials()
    {
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFname(): ?string
    {
        return $this->fname;
    }

    public function setFname(string $fname): self
    {
        $this->fname = $fname;

        return $this;
    }

    public function getLname(): ?string
    {
        return $this->lname;
    }

    public function setLname(string $lname): self
    {
        $this->lname = $lname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Messages>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Messages $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setSenderId($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getSenderId() === $this) {
                $message->setSenderId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, UsersBlocked>
     */
    public function getUsersBlockeds(): Collection
    {
        return $this->usersBlockeds;
    }

    public function addUsersBlocked(UsersBlocked $usersBlocked): self
    {
        if (!$this->usersBlockeds->contains($usersBlocked)) {
            $this->usersBlockeds->add($usersBlocked);
            $usersBlocked->addUserBlockingId($this);
        }

        return $this;
    }

    public function removeUsersBlocked(UsersBlocked $usersBlocked): self
    {
        if ($this->usersBlockeds->removeElement($usersBlocked)) {
            $usersBlocked->removeUserBlokingId($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, UsersDeleted>
     */
    public function getUsersDeleteds(): Collection
    {
        return $this->usersDeleteds;
    }

    public function addUsersDeleted(UsersDeleted $usersDeleted): self
    {
        if (!$this->usersDeleteds->contains($usersDeleted)) {
            $this->usersDeleteds->add($usersDeleted);
            $usersDeleted->addUserDeletingId($this);
        }

        return $this;
    }

    public function removeUsersDeleted(UsersDeleted $usersDeleted): self
    {
        if ($this->usersDeleteds->removeElement($usersDeleted)) {
            $usersDeleted->removeUserDeletingId($this);
        }

        return $this;
    }

    /**
     * transforme l'objet en chaine 
     */
    public function serialize()
    {
        // on return les infos qu'on veut conserver au niveau du user
        return serialize([
            $this->id,
            $this->email,
            $this->password
        ]);
    }
    /**
     * transforme la chaine en objet 
     */
    public function unserialize(string $data_serialise)
    {
        // genraliser un user apartir des information serialiser, les rendre en objet (User)
        list(
            $this->id,
            $this->email,
            $this->password
        ) = unserialize($data_serialise, ['allow_classes' => false]); // false pour ne pas instancier les classes dans la unserialisation
    }

    public function getProfileImg(): ?string
    {
        return $this->profile_img;
    }

    public function setProfileImg(string $profile_img): self
    {
        $this->profile_img = $profile_img;

        return $this;
    }

    public function getBackImg(): ?string
    {
        return $this->back_img;
    }

    public function setBackImg(string $back_img): self
    {
        $this->back_img = $back_img;

        return $this;
    }

    /*
    * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
    */
   public function setImageFile(?File $imageFile = null): void
   {
       $this->imageFile = $imageFile;

       if (null !== $imageFile) {
           // It is required that at least one field changes if you are using doctrine
           // otherwise the event listeners won't be called and the file is lost
           $this->updatedAt = new \DateTimeImmutable();
       }
   }

   public function getImageFile(): ?File
   {
       return $this->imageFile;
   }

    /**
     * Get the value of imageSize
     */ 
    public function getImageSize()
    {
        return $this->imageSize;
    }

    /**
     * Set the value of imageSize
     *
     * @return  self
     */ 
    public function setImageSize($imageSize)
    {
        $this->imageSize = $imageSize;

        return $this;
    }

    /**
     * Get the value of updatedAt
     */ 
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set the value of updatedAt
     *
     * @return  self
     */ 
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('fname', TextType::class, [
                'label' => "First Name"
            ])
            ->add('lname', TextType::class, [
                'label' => "Last Name"
            ])
            ->add('email', EmailType::class, [
                'label' => "Email"
            ])
            ->add('description', TextType::class, [
                'label' => "Actu"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
        ]);
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\UsersType;
use App\Repository\MessagesRepository;
use App\Repository\UsersRepository;
use App\Service\ServiceUsers;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/users')]
class UsersController extends AbstractController
{
    private $serv;

    public function __construct(ServiceUsers $serv)
    {
        $this->serv = $serv;
    }

    
    #[Route('/user-edit-{id}', name: 'users.edit', methods: ['POST'])]
    public function edit(Request $request, Users $user): Response
    {
        // return new JsonResponse($request->get('datas'));
        if($request->isXmlHttpRequest()){
            if($this->serv->persistUser($_POST, $user)){
                // si tout se passe bien on renvoie un pt message 

                return new JsonResponse([
                    'status' => "success",
                    'message' => "personal informations have been modified successfully !",
                ]);
            }else{
                // si tout se passe bien on renvoie un pt message 
                return new JsonResponse([
                    'status' => "failed",
                    'message' => "somthing went wrong !",
                ]);
            }
        }
    }

    #[Route('/message-section-{id}', 'message.section')]
    public function message(Request $request, Users $user, int $id, MessagesRepository $msgRepo){
        // on recupere le user sur sur le quel on a clicker ($user)
        if($request->isXmlHttpRequest()){
            /** @var Users */
            $user_sending = $this->getUser();
            $messages = $msgRepo->findMessages($user_sending->getId(), $id);
            return new JsonResponse([
                'content' => $this->renderView('pages/message-section.html.twig', [
                    'user' => $user,
                    'messages' => $messages == null ? null : $messages,
                    'user_sending' => $user_sending
                ]),
                'status' => 'success'
            ]);
        }
    }


    #[Route('/{id}', name: 'app_users_delete', methods: ['POST'])]
    public function delete(Request $request, Users $user, UsersRepository $usersRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $usersRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_users_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/users/_delete_form.html.twig
<form method="post" action="{{ path('app_users_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/users/_form.html.twig
{{ form_start(form) }}
    <div class="form-item">
        {{ form_row(form.fname) }}
    </div>
    <div class="form-item">
        {{ form_row(form.lname) }}
    </div>
    <div class="form-item">
        {{ form_row(form.email) }}
    </div>
    <div class="form-item">
        {{ form_row(form.description) }}
    </div>
    <button type="submit"><i class="fa-solid fa-check"></i></button>
{{ form_end(form) }}

templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Users{% endblock %}

{% block body %}
    <h1>Edit Users</h1>

    {{ include('users/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_users_index') }}">back to list</a>

    {{ include('users/_delete_form.html.twig') }}
{% endblock %}

templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users index{% endblock %}

{% block body %}
    <h1>Users index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>ImageSize</th>
                <th>UpdatedAt</th>
                <th>Id</th>
                <th>Fname</th>
                <th>Lname</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Password</th>
                <th>Status</th>
                <th>Description</th>
                <th>Profile_img</th>
                <th>Back_img</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.imageSize }}</td>
                <td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ user.id }}</td>
                <td>{{ user.fname }}</td>
                <td>{{ user.lname }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.phone }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.status ? 'Yes' : 'No' }}</td>
                <td>{{ user.description }}</td>
                <td>{{ user.profileImg }}</td>
                <td>{{ user.backImg }}</td>
                <td>
                    <a href="{{ path('app_users_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('app_users_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_users_new') }}">Create new</a>
{% endblock %}

templates/users/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Users{% endblock %}

{% block body %}
    <h1>Create new Users</h1>

    {{ include('users/_form.html.twig') }}

    <a href="{{ path('app_users_index') }}">back to list</a>
{% endblock %}

templates/users/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Users{% endblock %}

{% block body %}
    <h1>Users</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>ImageSize</th>
                <td>{{ user.imageSize }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Fname</th>
                <td>{{ user.fname }}</td>
            </tr>
            <tr>
                <th>Lname</th>
                <td>{{ user.lname }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ user.phone }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ user.status ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ user.description }}</td>
            </tr>
            <tr>
                <th>Profile_img</th>
                <td>{{ user.profileImg }}</td>
            </tr>
            <tr>
                <th>Back_img</th>
                <td>{{ user.backImg }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_users_index') }}">back to list</a>

    <a href="{{ path('app_users_edit', {'id': user.id}) }}">edit</a>

    {{ include('users/_delete_form.html.twig') }}
{% endblock %}